const AIR = 'AIR';
const CPT = 'CHECKPOINT';
const PTH = 'PATH';

const map = [
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, CPT, CPT, CPT, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PTH, PTH, CPT, CPT, CPT, AIR, AIR, AIR,
  AIR, AIR, AIR, CPT, CPT, CPT, AIR, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, AIR, CPT, CPT, CPT, AIR, AIR, AIR,
  AIR, AIR, AIR, CPT, CPT, CPT, AIR, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, AIR, CPT, CPT, CPT, AIR, AIR, AIR,
  AIR, AIR, AIR, CPT, CPT, CPT, AIR, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, AIR, CPT, CPT, CPT, AIR, AIR, AIR,
  AIR, AIR, AIR, CPT, CPT, CPT, AIR, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, PTH, AIR, CPT, CPT, CPT, AIR, AIR, AIR,
  AIR, AIR, AIR, CPT, CPT, CPT, PTH, PTH, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, CPT, CPT, CPT, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
  AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR,
];